config/routes.rb
Rails.application.routes.draw do
  resources :articles

  resources :regions
  resources :districts
  resources :users
  resources :sessions
  resources :lotteries

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'lichmothuong', to: 'welcome#lichmothuong'
  get 'kqxs', to: 'welcome#kqxs'
  get 'rss', to: 'welcome#rss'
  get 'about', to: 'welcome#about'
  get 'gallery', to: 'welcome#gallery'
  get 'contact', to: 'welcome#contact'

  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "DP's Serendipity" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div id="page" class="hfeed">
      <div id="wrapper">
        <header id="branding" role="banner">
          <h1 id="site-title"> 
            <a href="index.html" title="Serendipity" rel="home">
                <img src="/assets/style/images/logo.png" alt="Serendipity" />
            </a> 
          </h1>
          <div class="social">
            <div class="widget_search">
              <form method="get" class="search-form">
                <input type="submit" value="Search" class="search-submit-button" />
                <input type="text" value="Search" onfocus="this.value=''" onblur="this.value='Search'" name="s" class="search-text-box" />
              </form> 
            </div>
            <ul>
              <li><a href="#" target="_blank"><img src="/assets/style/images/icon-rss.png" alt="RSS" /></a></li>
              <li><a href="https://www.facebook.com/duyphan1206" target="_blank"><img src="/assets/style/images/icon-facebook.png" alt="Facebook" /></a></li>
              <li><a href="#" target="_blank"><img src="/assets/style/images/icon-twitter.png" alt="Twitter" /></a></li>
              <li><a href="#" target="_blank"><img src="/assets/style/images/icon-dribbble.png" alt="Dribbble" /></a></li>
              <li><a href="#" target="_blank"><img src="/assets/style/images/icon-linkedin.png" alt="LinkedIn" /></a></li>
              <li><a href="#" target="_blank"><img src="/assets/style/images/icon-pinterest.png" alt="Pinterest" /></a></li>
            </ul>
          </div>
          <nav id="access" class="access" role="navigation">
            <div id="menu" class="menu">
              <ul id="tiny">
                <li><a href="/">Blog</a>
                </li>
                <li><a href="/gallery">Gallery</a></li>
                <li><a href="/kqxs">VN Lottery</a>
                  <ul>
                    <li><a href="/kqxs">Kết Quả Xổ Số</a></li>
                    <li><a href="/lichmothuong">Lịch Mở Thưởng</a></li>
                    <li><a href="/doanmong">Mộng</a></li>
                  </ul>
                </li>
                <% unless administrator? %>
                <li><a href="/about">About</a></li>
                <li><a href="/contact">Contact</a></li>
                <% end %>
                <% if current_user %>
                  <% if administrator? %>
                    <li><%= link_to 'Users', users_path %></li>
                    <li><%= link_to 'Articles', articles_path %></li>
                  <% end %>
                  <li><%= link_to 'Log Out', logout_path %></li>
                <% else %>
                  <li><%= link_to 'Log In', new_session_path %></li>
                <% end %>
              </ul>
            </div>
            <div class="triangle-l"></div>
            <div class="triangle-r"></div>
          </nav>
          <!-- #access --> 
        </header>
        <div id="main">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <footer id="colophon" role="contentinfo">
          <div id="supplementary" class="four">
            <div id="first" class="widget-area" role="complementary">
              <aside class="widget">
                <h5 class="widget-title">Search</h5>  
                <form method="get" id="searchform" action="http://themes.iki-bir.com/serendipity-wp/">
                  <input type="text" class="field" name="s" id="s" title="Search" placeholder="" />
                  <input type="submit" class="submit" name="submit" id="searchsubmit" value="Search" />
                </form>
              </aside>
              
              <aside class="widget">
                <h5 class="widget-title">Recent Posts</h5>    
                  <ul>
                    <li><a href="#" title="A Wonderful Serenity">A Wonderful Serenity</a></li>
                    <li><a href="#" title="The Meridian Sun">The Meridian Sun</a></li>
                    <li><a href="#" title="Gallery Format">Gallery Format</a></li>
                    <li><a href="#" title="Gregor Samsa">Gregor Samsa</a></li>
                    <li><a href="#" title="A Life In The Day">A Life In The Day</a></li>
                  </ul>
              </aside>
            </div><!-- #first .widget-area -->
        
            <div id="second" class="widget-area" role="complementary">
              <aside class="widget">
                <h5 class="widget-title">Twitter</h5>
                <div id="twitter-wrapper">
                  <div id="twitter"></div>
                  <span class="username"><a href="https://www.facebook.com/duyphan1206">→ Follow @duyphan1206</a></span>
                </div>
              </aside>  
            </div><!-- #second .widget-area -->
        
            <div id="third" class="widget-area" role="complementary">
              <aside class="widget">
                <h5 class="widget-title">Tags</h5>
                  <div class="tagcloud"><a href='#' class='tag-link-37' title='1 topic' style='font-size: 8pt;'>blogroll</a>
                  <a href='#' class='tag-link-33' title='4 topics' style='font-size: 19.666666666667pt;'>daily</a>
                  <a href='#' class='tag-link-32' title='1 topic' style='font-size: 8pt;'>dialog</a>
                  <a href='#' class='tag-link-28' title='1 topic' style='font-size: 8pt;'>gallery</a>
                  <a href='#' class='tag-link-27' title='1 topic' style='font-size: 8pt;'>journal</a>
                  <a href='#' class='tag-link-36' title='1 topic' style='font-size: 8pt;'>link</a>
                  <a href='#' class='tag-link-31' title='1 topic' style='font-size: 8pt;'>motion</a>
                  <a href='#' class='tag-link-38' title='1 topic' style='font-size: 8pt;'>music</a>
                  <a href='#' class='tag-link-25' title='5 topics' style='font-size: 22pt;'>photo</a>
                  <a href='#' class='tag-link-26' title='2 topics' style='font-size: 13.25pt;'>professional</a>
                  <a href='#' class='tag-link-29' title='1 topic' style='font-size: 8pt;'>quotation</a>
                  <a href='#' class='tag-link-34' title='1 topic' style='font-size: 8pt;'>show</a>
                  <a href='#' class='tag-link-39' title='1 topic' style='font-size: 8pt;'>sound</a>
                  <a href='#' class='tag-link-35' title='1 topic' style='font-size: 8pt;'>tv</a>
                  <a href='#' class='tag-link-30' title='1 topic' style='font-size: 8pt;'>video</a></div>
              </aside>
              
              <aside class="widget">
                <h5 class="widget-title">Archives</h5>
                  <ul>
                    <li><a href='#' title='Jan 2015'>Jan 2015</a></li>
                    <li><a href='#' title='Feb 2015'>Feb 2015</a></li>
                  </ul>
              </aside>
            </div><!-- #third .widget-area -->
          
            <div id="fourth" class="widget-area" role="complementary">
              <aside class="widget">
                <h5 class="widget-title">About</h5>     
                <div class="textwidget">
                  <p> I'm Developer at AsNet Informatics and Trading Co., Ltd Da Nang, Viet Nam</p>
                  <p> I'm alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. </p>
                  <p> I'm so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents.</p>
                </div>
              </aside>
            </div><!-- #third .widget-area -->
          </div><!-- #supplementary -->
          <div id="site-generator">
            Copyright 2015 - DP's Serendipity
          </div>
        </footer><!-- #colophon -->
      </div>
    </div>
  </body>
</html>